/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.3.0 grouchy-aloysius
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span;

import com.lab5e.ApiException;
import com.lab5e.span.model.Gateway;
import com.lab5e.span.model.ListGatewayResponse;
import com.lab5e.span.model.ListNetworkResponse;
import com.lab5e.span.model.Status;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GatewaysApi
 */
@Ignore
public class GatewaysApiTest {

    private final GatewaysApi api = new GatewaysApi();

    
    /**
     * List gateways
     *
     * List the gatways for the network. Some of the gatways are built into Span and can&#39;t be deleted.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGatewaysTest() throws ApiException {
        String networkId = null;
                ListGatewayResponse response = api.listGateways(networkId);
        // TODO: test validations
    }
    
    /**
     * List networks
     *
     * List networks available to the collection. This will include the built-in networks in Span.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listNetworksTest() throws ApiException {
                ListNetworkResponse response = api.listNetworks();
        // TODO: test validations
    }
    
    /**
     * Retrieve gateway
     *
     * Get gateway information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveGatewayTest() throws ApiException {
        String networkId = null;
        String gatewayId = null;
                Gateway response = api.retrieveGateway(networkId, gatewayId);
        // TODO: test validations
    }
    
}
