/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.2 nonviolent-adelbert
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.DeviceConfig;
import com.lab5e.span.model.DeviceMetadata;
import com.lab5e.span.model.FirmwareMetadata;
import com.lab5e.span.model.MessageTransport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * This a device
 */
@ApiModel(description = "This a device")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-03-02T10:55:33.745521Z[Etc/UTC]")
public class Device {
  public static final String SERIALIZED_NAME_DEVICE_ID = "deviceId";
  @SerializedName(SERIALIZED_NAME_DEVICE_ID)
  private String deviceId;

  public static final String SERIALIZED_NAME_COLLECTION_ID = "collectionId";
  @SerializedName(SERIALIZED_NAME_COLLECTION_ID)
  private String collectionId;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private Map<String, String> tags = null;

  public static final String SERIALIZED_NAME_FIRMWARE = "firmware";
  @SerializedName(SERIALIZED_NAME_FIRMWARE)
  private FirmwareMetadata firmware;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  private DeviceConfig config;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private DeviceMetadata metadata;

  public static final String SERIALIZED_NAME_LAST_GATEWAY_ID = "lastGatewayId";
  @SerializedName(SERIALIZED_NAME_LAST_GATEWAY_ID)
  private String lastGatewayId;

  public static final String SERIALIZED_NAME_LAST_TRANSPORT = "lastTransport";
  @SerializedName(SERIALIZED_NAME_LAST_TRANSPORT)
  private MessageTransport lastTransport = MessageTransport.UNSPECIFIED;

  public static final String SERIALIZED_NAME_LAST_RECEIVED = "lastReceived";
  @SerializedName(SERIALIZED_NAME_LAST_RECEIVED)
  private String lastReceived;

  public static final String SERIALIZED_NAME_LAST_PAYLOAD = "lastPayload";
  @SerializedName(SERIALIZED_NAME_LAST_PAYLOAD)
  private byte[] lastPayload;

  public Device() { 
  }

  public Device deviceId(String deviceId) {
    
    this.deviceId = deviceId;
    return this;
  }

   /**
   * The device ID is assigned by the backend.
   * @return deviceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The device ID is assigned by the backend.")

  public String getDeviceId() {
    return deviceId;
  }


  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  public Device collectionId(String collectionId) {
    
    this.collectionId = collectionId;
    return this;
  }

   /**
   * Get collectionId
   * @return collectionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCollectionId() {
    return collectionId;
  }


  public void setCollectionId(String collectionId) {
    this.collectionId = collectionId;
  }


  public Device tags(Map<String, String> tags) {
    
    this.tags = tags;
    return this;
  }

  public Device putTagsItem(String key, String tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

   /**
   * Tags are metadata for the device that you can set. These are just strings.
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Tags are metadata for the device that you can set. These are just strings.")

  public Map<String, String> getTags() {
    return tags;
  }


  public void setTags(Map<String, String> tags) {
    this.tags = tags;
  }


  public Device firmware(FirmwareMetadata firmware) {
    
    this.firmware = firmware;
    return this;
  }

   /**
   * Get firmware
   * @return firmware
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FirmwareMetadata getFirmware() {
    return firmware;
  }


  public void setFirmware(FirmwareMetadata firmware) {
    this.firmware = firmware;
  }


  public Device config(DeviceConfig config) {
    
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceConfig getConfig() {
    return config;
  }


  public void setConfig(DeviceConfig config) {
    this.config = config;
  }


  public Device metadata(DeviceMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DeviceMetadata getMetadata() {
    return metadata;
  }


  public void setMetadata(DeviceMetadata metadata) {
    this.metadata = metadata;
  }


  public Device lastGatewayId(String lastGatewayId) {
    
    this.lastGatewayId = lastGatewayId;
    return this;
  }

   /**
   * Get lastGatewayId
   * @return lastGatewayId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastGatewayId() {
    return lastGatewayId;
  }


  public void setLastGatewayId(String lastGatewayId) {
    this.lastGatewayId = lastGatewayId;
  }


  public Device lastTransport(MessageTransport lastTransport) {
    
    this.lastTransport = lastTransport;
    return this;
  }

   /**
   * Get lastTransport
   * @return lastTransport
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MessageTransport getLastTransport() {
    return lastTransport;
  }


  public void setLastTransport(MessageTransport lastTransport) {
    this.lastTransport = lastTransport;
  }


  public Device lastReceived(String lastReceived) {
    
    this.lastReceived = lastReceived;
    return this;
  }

   /**
   * Get lastReceived
   * @return lastReceived
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastReceived() {
    return lastReceived;
  }


  public void setLastReceived(String lastReceived) {
    this.lastReceived = lastReceived;
  }


  public Device lastPayload(byte[] lastPayload) {
    
    this.lastPayload = lastPayload;
    return this;
  }

   /**
   * Get lastPayload
   * @return lastPayload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public byte[] getLastPayload() {
    return lastPayload;
  }


  public void setLastPayload(byte[] lastPayload) {
    this.lastPayload = lastPayload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Device device = (Device) o;
    return Objects.equals(this.deviceId, device.deviceId) &&
        Objects.equals(this.collectionId, device.collectionId) &&
        Objects.equals(this.tags, device.tags) &&
        Objects.equals(this.firmware, device.firmware) &&
        Objects.equals(this.config, device.config) &&
        Objects.equals(this.metadata, device.metadata) &&
        Objects.equals(this.lastGatewayId, device.lastGatewayId) &&
        Objects.equals(this.lastTransport, device.lastTransport) &&
        Objects.equals(this.lastReceived, device.lastReceived) &&
        Arrays.equals(this.lastPayload, device.lastPayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, collectionId, tags, firmware, config, metadata, lastGatewayId, lastTransport, lastReceived, Arrays.hashCode(lastPayload));
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Device {\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    collectionId: ").append(toIndentedString(collectionId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    firmware: ").append(toIndentedString(firmware)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    lastGatewayId: ").append(toIndentedString(lastGatewayId)).append("\n");
    sb.append("    lastTransport: ").append(toIndentedString(lastTransport)).append("\n");
    sb.append("    lastReceived: ").append(toIndentedString(lastReceived)).append("\n");
    sb.append("    lastPayload: ").append(toIndentedString(lastPayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

