/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.lab5e.JSON;

/**
 * GatewayInetConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-11T21:56:14.173008Z[Etc/UTC]")
public class GatewayInetConfig {
  public static final String SERIALIZED_NAME_DTLS_ENDPOINT = "dtlsEndpoint";
  @SerializedName(SERIALIZED_NAME_DTLS_ENDPOINT)
  private String dtlsEndpoint;

  public static final String SERIALIZED_NAME_COAP_ENDPOINT = "coapEndpoint";
  @SerializedName(SERIALIZED_NAME_COAP_ENDPOINT)
  private String coapEndpoint;

  public static final String SERIALIZED_NAME_MQTT_ENDPOINT = "mqttEndpoint";
  @SerializedName(SERIALIZED_NAME_MQTT_ENDPOINT)
  private String mqttEndpoint;

  public GatewayInetConfig() {
  }

  public GatewayInetConfig dtlsEndpoint(String dtlsEndpoint) {
    
    this.dtlsEndpoint = dtlsEndpoint;
    return this;
  }

   /**
   * Get dtlsEndpoint
   * @return dtlsEndpoint
  **/
  @javax.annotation.Nullable

  public String getDtlsEndpoint() {
    return dtlsEndpoint;
  }


  public void setDtlsEndpoint(String dtlsEndpoint) {
    this.dtlsEndpoint = dtlsEndpoint;
  }


  public GatewayInetConfig coapEndpoint(String coapEndpoint) {
    
    this.coapEndpoint = coapEndpoint;
    return this;
  }

   /**
   * Get coapEndpoint
   * @return coapEndpoint
  **/
  @javax.annotation.Nullable

  public String getCoapEndpoint() {
    return coapEndpoint;
  }


  public void setCoapEndpoint(String coapEndpoint) {
    this.coapEndpoint = coapEndpoint;
  }


  public GatewayInetConfig mqttEndpoint(String mqttEndpoint) {
    
    this.mqttEndpoint = mqttEndpoint;
    return this;
  }

   /**
   * Get mqttEndpoint
   * @return mqttEndpoint
  **/
  @javax.annotation.Nullable

  public String getMqttEndpoint() {
    return mqttEndpoint;
  }


  public void setMqttEndpoint(String mqttEndpoint) {
    this.mqttEndpoint = mqttEndpoint;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GatewayInetConfig gatewayInetConfig = (GatewayInetConfig) o;
    return Objects.equals(this.dtlsEndpoint, gatewayInetConfig.dtlsEndpoint) &&
        Objects.equals(this.coapEndpoint, gatewayInetConfig.coapEndpoint) &&
        Objects.equals(this.mqttEndpoint, gatewayInetConfig.mqttEndpoint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dtlsEndpoint, coapEndpoint, mqttEndpoint);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GatewayInetConfig {\n");
    sb.append("    dtlsEndpoint: ").append(toIndentedString(dtlsEndpoint)).append("\n");
    sb.append("    coapEndpoint: ").append(toIndentedString(coapEndpoint)).append("\n");
    sb.append("    mqttEndpoint: ").append(toIndentedString(mqttEndpoint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("dtlsEndpoint");
    openapiFields.add("coapEndpoint");
    openapiFields.add("mqttEndpoint");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GatewayInetConfig
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GatewayInetConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GatewayInetConfig is not found in the empty JSON string", GatewayInetConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GatewayInetConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GatewayInetConfig` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("dtlsEndpoint") != null && !jsonObj.get("dtlsEndpoint").isJsonNull()) && !jsonObj.get("dtlsEndpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dtlsEndpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dtlsEndpoint").toString()));
      }
      if ((jsonObj.get("coapEndpoint") != null && !jsonObj.get("coapEndpoint").isJsonNull()) && !jsonObj.get("coapEndpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `coapEndpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("coapEndpoint").toString()));
      }
      if ((jsonObj.get("mqttEndpoint") != null && !jsonObj.get("mqttEndpoint").isJsonNull()) && !jsonObj.get("mqttEndpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mqttEndpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mqttEndpoint").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GatewayInetConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GatewayInetConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GatewayInetConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GatewayInetConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<GatewayInetConfig>() {
           @Override
           public void write(JsonWriter out, GatewayInetConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GatewayInetConfig read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GatewayInetConfig given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GatewayInetConfig
  * @throws IOException if the JSON string is invalid with respect to GatewayInetConfig
  */
  public static GatewayInetConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GatewayInetConfig.class);
  }

 /**
  * Convert an instance of GatewayInetConfig to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

