/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.lab5e.JSON;

/**
 * The image version log contains all reported versions and firmware images  by a device. The entries in the version log is independent of the image list;  if an image is removed the entry will remain in the version log.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-11T21:56:14.173008Z[Etc/UTC]")
public class ImageVersionEntry {
  public static final String SERIALIZED_NAME_DEVICE_ID = "deviceId";
  @SerializedName(SERIALIZED_NAME_DEVICE_ID)
  private String deviceId;

  public static final String SERIALIZED_NAME_IMAGE_ID = "imageId";
  @SerializedName(SERIALIZED_NAME_IMAGE_ID)
  private String imageId;

  public static final String SERIALIZED_NAME_IMAGE_VERSION = "imageVersion";
  @SerializedName(SERIALIZED_NAME_IMAGE_VERSION)
  private String imageVersion;

  public static final String SERIALIZED_NAME_IMAGE_LABEL = "imageLabel";
  @SerializedName(SERIALIZED_NAME_IMAGE_LABEL)
  private String imageLabel;

  public static final String SERIALIZED_NAME_REPORTED = "reported";
  @SerializedName(SERIALIZED_NAME_REPORTED)
  private String reported;

  public ImageVersionEntry() {
  }

  public ImageVersionEntry deviceId(String deviceId) {
    
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @javax.annotation.Nullable

  public String getDeviceId() {
    return deviceId;
  }


  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  public ImageVersionEntry imageId(String imageId) {
    
    this.imageId = imageId;
    return this;
  }

   /**
   * Get imageId
   * @return imageId
  **/
  @javax.annotation.Nullable

  public String getImageId() {
    return imageId;
  }


  public void setImageId(String imageId) {
    this.imageId = imageId;
  }


  public ImageVersionEntry imageVersion(String imageVersion) {
    
    this.imageVersion = imageVersion;
    return this;
  }

   /**
   * Get imageVersion
   * @return imageVersion
  **/
  @javax.annotation.Nullable

  public String getImageVersion() {
    return imageVersion;
  }


  public void setImageVersion(String imageVersion) {
    this.imageVersion = imageVersion;
  }


  public ImageVersionEntry imageLabel(String imageLabel) {
    
    this.imageLabel = imageLabel;
    return this;
  }

   /**
   * Get imageLabel
   * @return imageLabel
  **/
  @javax.annotation.Nullable

  public String getImageLabel() {
    return imageLabel;
  }


  public void setImageLabel(String imageLabel) {
    this.imageLabel = imageLabel;
  }


  public ImageVersionEntry reported(String reported) {
    
    this.reported = reported;
    return this;
  }

   /**
   * Get reported
   * @return reported
  **/
  @javax.annotation.Nullable

  public String getReported() {
    return reported;
  }


  public void setReported(String reported) {
    this.reported = reported;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageVersionEntry imageVersionEntry = (ImageVersionEntry) o;
    return Objects.equals(this.deviceId, imageVersionEntry.deviceId) &&
        Objects.equals(this.imageId, imageVersionEntry.imageId) &&
        Objects.equals(this.imageVersion, imageVersionEntry.imageVersion) &&
        Objects.equals(this.imageLabel, imageVersionEntry.imageLabel) &&
        Objects.equals(this.reported, imageVersionEntry.reported);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, imageId, imageVersion, imageLabel, reported);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageVersionEntry {\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    imageId: ").append(toIndentedString(imageId)).append("\n");
    sb.append("    imageVersion: ").append(toIndentedString(imageVersion)).append("\n");
    sb.append("    imageLabel: ").append(toIndentedString(imageLabel)).append("\n");
    sb.append("    reported: ").append(toIndentedString(reported)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deviceId");
    openapiFields.add("imageId");
    openapiFields.add("imageVersion");
    openapiFields.add("imageLabel");
    openapiFields.add("reported");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ImageVersionEntry
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ImageVersionEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ImageVersionEntry is not found in the empty JSON string", ImageVersionEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ImageVersionEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ImageVersionEntry` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("deviceId") != null && !jsonObj.get("deviceId").isJsonNull()) && !jsonObj.get("deviceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deviceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deviceId").toString()));
      }
      if ((jsonObj.get("imageId") != null && !jsonObj.get("imageId").isJsonNull()) && !jsonObj.get("imageId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `imageId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("imageId").toString()));
      }
      if ((jsonObj.get("imageVersion") != null && !jsonObj.get("imageVersion").isJsonNull()) && !jsonObj.get("imageVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `imageVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("imageVersion").toString()));
      }
      if ((jsonObj.get("imageLabel") != null && !jsonObj.get("imageLabel").isJsonNull()) && !jsonObj.get("imageLabel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `imageLabel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("imageLabel").toString()));
      }
      if ((jsonObj.get("reported") != null && !jsonObj.get("reported").isJsonNull()) && !jsonObj.get("reported").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `reported` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reported").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ImageVersionEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ImageVersionEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ImageVersionEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ImageVersionEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<ImageVersionEntry>() {
           @Override
           public void write(JsonWriter out, ImageVersionEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ImageVersionEntry read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ImageVersionEntry given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ImageVersionEntry
  * @throws IOException if the JSON string is invalid with respect to ImageVersionEntry
  */
  public static ImageVersionEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ImageVersionEntry.class);
  }

 /**
  * Convert an instance of ImageVersionEntry to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

