/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.16 spooky-devante
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.NetworkOperator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeviceMetadata
 */
public class DeviceMetadataTest {
    private final DeviceMetadata model = new DeviceMetadata();

    /**
     * Model tests for DeviceMetadata
     */
    @Test
    public void testDeviceMetadata() {
        // TODO: test DeviceMetadata
    }

    /**
     * Test the property 'simOperator'
     */
    @Test
    public void simOperatorTest() {
        // TODO: test simOperator
    }

}
