/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.6.0 truthful-holli
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lab5e.span.model.DeviceConfig;
import com.lab5e.span.model.DeviceMetadata;
import com.lab5e.span.model.FirmwareMetadata;
import com.lab5e.span.model.MessageTransport;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Device
 */
public class DeviceTest {
    private final Device model = new Device();

    /**
     * Model tests for Device
     */
    @Test
    public void testDevice() {
        // TODO: test Device
    }

    /**
     * Test the property 'deviceId'
     */
    @Test
    public void deviceIdTest() {
        // TODO: test deviceId
    }

    /**
     * Test the property 'collectionId'
     */
    @Test
    public void collectionIdTest() {
        // TODO: test collectionId
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'firmware'
     */
    @Test
    public void firmwareTest() {
        // TODO: test firmware
    }

    /**
     * Test the property 'config'
     */
    @Test
    public void configTest() {
        // TODO: test config
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'lastGatewayId'
     */
    @Test
    public void lastGatewayIdTest() {
        // TODO: test lastGatewayId
    }

    /**
     * Test the property 'lastTransport'
     */
    @Test
    public void lastTransportTest() {
        // TODO: test lastTransport
    }

    /**
     * Test the property 'lastReceived'
     */
    @Test
    public void lastReceivedTest() {
        // TODO: test lastReceived
    }

    /**
     * Test the property 'lastPayload'
     */
    @Test
    public void lastPayloadTest() {
        // TODO: test lastPayload
    }

}
