/*
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lab5e.span.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DeviceStats
 */
public class DeviceStatsTest {
    private final DeviceStats model = new DeviceStats();

    /**
     * Model tests for DeviceStats
     */
    @Test
    public void testDeviceStats() {
        // TODO: test DeviceStats
    }

    /**
     * Test the property 'bytesUpstream'
     */
    @Test
    public void bytesUpstreamTest() {
        // TODO: test bytesUpstream
    }

    /**
     * Test the property 'bytesDownstream'
     */
    @Test
    public void bytesDownstreamTest() {
        // TODO: test bytesDownstream
    }

    /**
     * Test the property 'messagesUpstream'
     */
    @Test
    public void messagesUpstreamTest() {
        // TODO: test messagesUpstream
    }

    /**
     * Test the property 'messagesDownstream'
     */
    @Test
    public void messagesDownstreamTest() {
        // TODO: test messagesDownstream
    }

    /**
     * Test the property 'sessionCount'
     */
    @Test
    public void sessionCountTest() {
        // TODO: test sessionCount
    }

}
